# Generated by Django 5.0.3 on 2024-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_remove_footerslider_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='number_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='number_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
