# Generated by Django 5.0.3 on 2024-03-06 06:26

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_master_number_first_alter_master_number_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('priority', models.IntegerField(default=0)),
                ('slug', models.CharField(default='', max_length=250)),
                ('available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[300, 300], upload_to='popular_category/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.category')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, default='', max_length=250)),
                ('priority', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 400], upload_to='slider/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.category')),
            ],
        ),
        migrations.CreateModel(
            name='SliderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, default='', max_length=250)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[200, 200], upload_to='slider/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.category')),
            ],
        ),
    ]
