# Generated by Django 5.0.3 on 2024-03-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='store',
            name='telegram_link',
        ),
    ]
