# Generated by Django 5.0.3 on 2024-03-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_remove_store_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
