# Generated by Django 5.0.3 on 2024-03-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_store_instagram_link_store_telegram_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='map',
        ),
    ]
