# Generated by Django 5.0.3 on 2024-03-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_remove_store_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
