# Generated by Django 5.0.3 on 2024-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(blank=True, max_length=225, null=True)),
                ('start_day_time', models.CharField(blank=True, max_length=225, null=True)),
                ('finish_day', models.CharField(blank=True, max_length=225, null=True)),
                ('finish_day_time', models.CharField(blank=True, max_length=225, null=True)),
                ('addition_day', models.CharField(blank=True, max_length=225, null=True)),
                ('addition_day_time', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('phone_first', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_second', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('map', models.TextField()),
            ],
        ),
    ]
