# Generated by Django 5.0.3 on 2024-03-07 07:23

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('subtitle', models.CharField(blank=True, max_length=225, null=True)),
                ('slug', models.CharField(default='', max_length=250)),
                ('description', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('image_max', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 400], upload_to='product/')),
                ('image_min', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[300, 300], upload_to='product/')),
                ('available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_full', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 400], upload_to='products/')),
                ('img_min', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[300, 300], upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.product')),
            ],
        ),
    ]
