# Generated by Django 5.0.3 on 2024-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
