# Generated by Django 5.0.3 on 2024-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_alter_product_discount_alter_product_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nav',
            field=models.BooleanField(default=False),
        ),
    ]
