# Generated by Django 5.0.3 on 2024-03-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_category_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
