# Generated by Django 5.0.3 on 2024-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='sub_city',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
