# Generated by Django 5.0.3 on 2024-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_price',
            field=models.BooleanField(default=True),
        ),
    ]
