# Generated by Django 5.0.3 on 2024-03-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_product_available_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='district_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='region_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
