# Generated by Django 5.0.3 on 2024-03-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_master_district_name_master_region_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-priority',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-priority',)},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('-priority',)},
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='slidercategory',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.category'),
        ),
    ]
