# Generated by Django 5.0.3 on 2024-03-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_popularcategory_title_alter_popularcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcategory',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
