# Generated by Django 5.0.3 on 2024-03-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_popularcategory_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularcategory',
            options={'ordering': ('-priority',)},
        ),
    ]
