# Generated by Django 5.0.3 on 2024-03-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_alter_popularcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
